pipeline {
    agent any

    triggers {
        githubPush()
    }

    tools {
        nodejs 'Node 20' 
    }

    environment {
        // Ensure npm is available in the path
        PATH = "${tool 'Node 20'}/bin;${env.PATH}"
        
        // Define Docker image details
        IMAGE_NAME = "cybersafe-app"
        IMAGE_TAG = "v${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm ci' 
            }
        }

        stage('Lint Code') {
            steps {
                bat 'npm run lint'
            }
        }

        stage('Unit Tests') {
            steps {
                bat 'npm run test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarScanner' 
                    withSonarQubeEnv('SonarQube') {
                        bat "\"${scannerHome}\\bin\\sonar-scanner.bat\""
                    }
                }
            }
        }

        stage('Build Application') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building Docker Image...'
                    bat "docker build -t %IMAGE_NAME%:%IMAGE_TAG% ."
                    bat "docker tag %IMAGE_NAME%:%IMAGE_TAG% %IMAGE_NAME%:latest"
                }
            }
        }

        stage('Trivy Security Scan') {
            steps {
                script {
                    echo 'Scanning Docker Image...'
                    // 1. Download Template
                    bat "curl -L -o html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl"

                    // 2. HTML Report
                    bat "trivy image --format template --template \"@html.tpl\" -o trivy-report.html %IMAGE_NAME%:latest"
                    
                    // 3. JSON Report (Required for AI Analysis)
                    bat "trivy image --format json -o trivy-report.json %IMAGE_NAME%:latest"

                    // 4. Pass/Fail Check
                    bat "trivy image --exit-code 1 --severity CRITICAL %IMAGE_NAME%:latest"
                }
            }
        }

        stage('AI Analysis') {
            steps {
                // Ensure you added 'groq-api-key' in Jenkins Credentials!
                withCredentials([string(credentialsId: 'groq-api-key', variable: 'GROQ_API_KEY')]) {
                    script {
                        echo 'Asking Groq AI to analyze reports...'
                        bat "node ai-analyst.js"
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                // Archive artifacts first
                archiveArtifacts artifacts: 'trivy-report.html, trivy-report.json, ai-advice.txt', fingerprint: true, allowEmptyArchive: true

                // --- DISCORD NOTIFICATION ---
                withCredentials([string(credentialsId: 'discord-webhook-url', variable: 'DISCORD_WEBHOOK')]) {
                    // Pass the Build Status as an environment variable
                    withEnv(["BUILD_STATUS=${currentBuild.currentResult}"]) {
                         bat "node discord-notify.js"
                    }
                }

                // --- EMAIL NOTIFICATION ---
                def toEmail = "sahilrane249@gmail.com" 
                
                // Read the HTML content generated by AI
                def aiMessage = "<p>No AI analysis generated.</p>"
                if (fileExists('ai-advice.txt')) {
                    aiMessage = readFile(file: 'ai-advice.txt', encoding: 'UTF-8')
                }
                
                try {
                    // HTML Email Body
                    def emailBody = """
                        <html>
                        <body style="font-family: Arial, sans-serif;">
                            <h2>Jenkins Build Status: <span style="color: ${currentBuild.currentResult == 'SUCCESS' ? 'green' : 'red'}">${currentBuild.currentResult}</span></h2>
                            <p>
                                <b>Job:</b> ${env.JOB_NAME}<br>
                                <b>Build Number:</b> ${env.BUILD_NUMBER}<br>
                                <b>Docker Image:</b> ${env.IMAGE_NAME}:${env.IMAGE_TAG}
                            </p>
                            
                            <hr>
                            ${aiMessage}
                            <hr>
                            
                            <p>
                                <a href="${env.BUILD_URL}">View Console Output</a>
                            </p>
                        </body>
                        </html>
                    """

                    mail to: toEmail,
                         subject: "Build ${env.BUILD_NUMBER}: Security Report (${currentBuild.currentResult})",
                         body: emailBody,
                         mimeType: 'text/html', // <--- THIS TURNS ON THE FORMATTING
                         charset: 'UTF-8'
                } catch (Exception e) {
                    echo "Failed to send email: ${e.message}"
                }
            }
        }
        failure {
            echo 'Build failed. Email sent.'
        }
    }
}